#Model
model: Models.model_acc_only.ActTransformerAcc

#model_args
model_args:
  acc_frames : 256
  num_joints : 31 
  num_classes : 11
  acc_embed : 32 
  adepth : 4
  num_heads : 4


#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
epochs: 200

#dataloader
feeder: Make_Dataset.UTD_mm

train_feeder_args:
  npz_file: data/UTD_MAAD/utd_train4p.npz
  batch_size: 16

val_feeder_args:
  npz_file: data/UTD_MAAD/utd_val2p.npz
  batch_size: 16

test_feeder_args: 
  npz_file: data/UTD_MAAD/utd_test2p.npz

seed: 2 
optimizer: Adam

