# KalmanGatedHierarchical + Linear KF (Euler)

model: Models.kalman_gated_hierarchical.KalmanGatedHierarchical

model_args:
  imu_frames: 128
  imu_channels: 7
  num_heads: 4
  num_layers: 2
  embed_dim: 64
  dropout: 0.4
  activation: gelu
  norm_first: True
  se_reduction: 4
  acc_channels: 4
  use_multi_scale: True
  use_hierarchical_gate: True
  use_residual_gate: True
  feature_noise: 0.1

dataset_args:
  kalman_filter_type: linear
  kalman_output_format: euler
  kalman_Q_orientation: 0.005
  kalman_Q_rate: 0.01
  kalman_R_acc: 0.05
  kalman_R_gyro: 0.1
