teacher_model: Models.st_cvtransformer.MMTransformer
student_model: Models.transformer.TransModel
dataset: smartfallmm

# train_subjects: [2, 4,5, 6,7,9 ,10,11, 14,15,16,17,19,21,22,23, 25,26]
# test_subjects: [18]
# subjects: [29,31, 32, 34,35,36,37]

subjects: [5,7,10,11,15,16,17,18,19,21,22,23]

#model_args
teacher_args:
  acc_frames : 128
  num_joints : 32
  num_classes : 8
  spatial_embed : 64
  adepth : 2
  sdepth : 2
  num_heads : 2
  mocap_frames: 128
  num_patch: 4
  acc_coords: 3
  drop_path_rate: 0.5
  drop_rate: 0.5
  attn_drop_rate: 0.5

student_args: 
  mocap_frames: 128
  acc_frames : 128
  num_joints : 32
  num_classes : 8
  acc_embed : 64
  adepth : 4
  num_heads : 2
  acc_coords: 3

#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 8
test_batch_size: 8
val_batch_size : 8
num_epoch: 120

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

distill_loss: loss.SemanticLoss
distill_args: 
  T : 2
  alpha: 0.7

student_loss: loss.BCE


train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 8

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 8

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 8

seed: 2 
optimizer: sgd