teacher_model: Models.st_cvtransformer.MMTransformer
student_model: Models.transformer.TransModel
dataset: smartfallmm

# train_subjects: 1
# test_subjects: [18]
subjects: [1,2, 3, 4, 5,7,8,9, 10,11, 12,13,14,15, 16, 17, 18,47, 19,22,23]
#subjects : [29,30,31, 32, 34, 35, 36, 37,38,39, 40, 41, 42, 43, 44, 45, 46]

#model_args
teacher_args:
  acc_frames : 128
  num_joints : 32
  num_classes : 8
  spatial_embed : 32
  adepth : 2
  sdepth : 2
  num_heads : 2
  mocap_frames: 128
  num_patch: 4

student_args: 
  num_layers : 2
  norm_first : True
  embed_dim: 32
  activation: relu 
  acc_coords : 4
  num_classes: 9
  acc_frames : 128
  mocap_frames : 128
  num_heads: 2

#optim
# weight_decay: 0.0004
# base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 300

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

distill_loss: loss.SemanticLoss
distill_args: 
  T : 2
  alpha: 0.7

student_loss: loss.BCE


train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: sgd