model: Models.transformer.TransModel
dataset: smartfallmm

#subjects: [1,2, 3, 4, 5,7,8,9, 10,11, 12,13,14,15, 16, 17, 18,47,19,22,23]
subjects: [29,30,31, 32, 34, 35, 36, 37,38,39, 40, 41, 42, 43, 44, 45, 46]

model_args:
  num_layers : 2
  norm_first : True
  embed_dim: 32
  activation: relu 
  acc_coords : 4
  num_classes: 9
  acc_frames : 128
  mocap_frames : 128
  num_heads: 2

dataset_args: 
 mode: 'avg_pool'
 max_length: 128 
 task : 'fd'
 modalities: ['skeleton', 'accelerometer']
 age_group: ['young', 'old']
 sensors: ['watch']

batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 300

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16

val_feeder_args:
  batch_size: 16

test_feeder_args: 
  batch_size: 16

seed: 2 
optimizer: sgd